### PR TITLE
Initial check-in of Neon Shooter Sample

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
- Only implemented on GL platform currently (templates exist for other platforms but have not been configured)
- Currently not working, used to function but isn't working with 3.2 Build

### CODE REVIEW

**Comment by tomspilman** [comment]
Thanks!

**Comment by tomspilman** [comment]
This is conflicted after I merged your other PR.  Can you fix it please?

**Comment by CartBlanche** [comment]
Just a quick thought. Any chance the Readme.md can include a link to a a screen shot of the sample running on one of the platforms. Just so people downloading the sample get a rough idea of what the sample looks like while running?

**Comment by SimonDarksideJ** [comment]
That sounds like a great idea Dom, would also improve the quality view of each sample.
Can this be raised as an enhancement on the project @tomspilman 
probably need to come up with a brief template so the documentation is the same for all samples and include the details you mentioned Dom.

**Comment by SimonDarksideJ** [comment]
Right @tomspilman I've updated the branch with the updated develop branch post the spacewar merge.
This should have fixed the conflicts

**Comment by tomspilman** [comment]
@CartBlanche - #14

**Pull request merged**
