### PR TITLE
Feature/ship game

### PR DESCRIPTION
**Pull request by NemoKradXNA**
Fixes to allow the Ship game to run on both DX and GL builds
#68 
#69 
#70

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Two observations from the updated build:
1. The ship selection reticule is missing in the DX build, as shown on the ship selection screen
image

2. The scene on both GL and DX now appear much darker than it was
image

Original
image

Both are non-critical as the focus is to get the sample running first on all platforms.

**Comment by NemoKradXNA** [comment]
Looking at that UI issue next.

I flipped the lighting on the normalmapping.fx, ill put that back.

You really need to bin the level 1 mesh off as it has a few primitives that  have the wrong winding order.

I might look a t restructuring the whole thing if I have time.

**Comment by NemoKradXNA** [comment]
Next PR will have the UI fix.
image
And the lighting calculations fixed
image


I have noticed when a missile is fired, there is a train artifact. Not sure what's causing that yet.

**Comment by NemoKradXNA** [comment]
Looks like the particle artifact is just a stray particle as the missile is launched, slowing the missile right down showed that the render of particles looks fine. So I won't bee looking into that anymore.

**Review by SimonDarksideJ — APPROVED** [review]

**Comment by CartBlanche** [comment]
Thanks @NemoKradXNA for helping us getting this last, but critical, part working!

**Pull request merged**
