### PR TITLE
Mgcb update

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
- Updated all samples to use the new MG Content Builder tool

**Note, from this point you need to install the latest MG MSI installer to install the MGCB tool, which can be located from the Development Builds section at:
http://www.monogame.net/downloads/

Current Known Issues :
- SpaceWar is unable to process the XACT file
- iOS build complains about the EXIT() function - says it is no longer used
- Linux build fails to package the WMA file - Song processor content builder fail?

### CODE REVIEW

**Comment by tomspilman** [comment]
Why are you updating the "master" branch here?  Shouldn't this PR be applied to the "develop" branch?

**Comment by SimonDarksideJ** [comment]
Hmm, it shouldn't be as I did it as a branch of the develop branch. Possibly due to master being the default branch it selected master as the target.
I'll check and update and resubmit if ness

**Comment by tomspilman** [comment]
>  Possibly due to master being the default branch it selected master as the target.

Yep...  that is exactly what happened.

**Comment by SimonDarksideJ** [comment]
Right, resubmitted PR #31. now targets develop branch

**Pull request closed without merging**
