### PR TITLE
Platformer 2d sample

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
Finally finished testing and polishing the Platformer 2D sample for the MonoGame 3.2 release.

Covers all currently supported (public) platforms, including:
- Android (using MG 3.2 NuGet)
- iOS (using MG 3.2 NuGet)
- MacOS (using MG 3.2 NuGet)
- Ouya (Using direct ref to source - update when testing)
- PSM (Using direct ref to source - update when testing)
- WindowsGL (using MG 3.2 NuGet)
- Windows 8 (using MG 3.2 NuGet)
- Windows Phone (using MG 3.2 NuGet)

All tested and working properly.

### CODE REVIEW

**Comment by tomspilman** [comment]
Looking thru the repo which is easier to review...

 https://github.com/DDReaper/Samples/tree/Platformer2D-Sample

**Comment by SimonDarksideJ** [comment]
Yeah, the commits evolved over time.  Should get easier as we add more samples.
This one is a basic smash and grab to launch the same project on all platforms.

Future samples should get more evolved and handle trickier scenarios, like files, web, more inputs, shaders, etc

**Comment by tomspilman** [comment]
What is the Sample-Template for?

Also what is ContentBuilder?

**Comment by tomspilman** [comment]
Should we make the samples use the MonoGame content pipeline instead of the XNA one?  It would force us to fix any problems that arise.  Dogfooding would be good for us.

**Comment by CartBlanche** [comment]
To do you think it would be a good idea to make this a 2 step process? Accept this PR, then get a second PR with the MonoGame content pipeline change?

**Comment by SimonDarksideJ** [comment]
That sounds fair, then we have one checkpoint as it is and then an upgraded solution with the new pipeline.
plus I've not tried the new pipeline yet 😆

The sample template isn't crucial, I only had that to making new samples easier in the same structure.

If you want it taken out that's no worry

**Comment by tomspilman** [comment]
> To do you think it would be a good idea to make this a 2 step process? 

Sure... the content work will take a little time to setup.

> The sample template isn't crucial

Then lets remove it and i'll merge it.

**Comment by SimonDarksideJ** [comment]
Right, I'll sort that tonight

**Comment by SimonDarksideJ** [comment]
Done.

**Pull request merged**
