### PR TITLE
Added WindowsDX platform

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
As per request  #4, I've added the WindowsDX platform using 3.2 installed assemblies (requires MonoGame installed DLL's)

Renamed GL platform folder to WindowsGL to avoid confusion with DX

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Note, also tidied up the assemblyinfo.cs in the GL build as it had some Android references?? very odd.
Assembly info files should be kept separate for each platform to allow different versioning

**Comment by tomspilman** [comment]
I guess I should merge this into develop too after I merge this.

**Comment by tomspilman** [comment]
Oops... look like you missed the solution.

**Comment by SimonDarksideJ** [comment]
Yeah noted. Found an open window after I finished committing.  Already corrected and another PR submitted

**Pull request merged**
