### PR TITLE
Some changes to projects/solutions

### PR DESCRIPTION
**Pull request by nkast**
-Add the Content folder as a link.
(only for the platforms I could test.)

-Convert Samples-Content.sln to VS2010 version.
VS2012 doesn't support XNA (unless if added by hand). This change will
open VS2010 for this solution.

### CODE REVIEW

**Comment by tomspilman** [comment]
@DDReaper - This make sense?

**Comment by SimonDarksideJ** [comment]
Hmm
The Content folders are already just links.  There is a single content folder in the samples top folder (e.g. Platformer2D\Content) and all projects link to the content builder solution output.
I don't think we should have a single content project for ALL samples as this would get very messy very quickly.
That being said, having a way to show platform variance for content would be good (as it doesn't do it now) where some platforms would use resized content over the HD versions.  Welcome to ideas on how to do that best practice.  Would also have to work with the new Content Builder request.
**Edit**, that'll teach me for commenting before examining the changes.
If that recursive option works, then that's fine but what about projects that need different assets? Mobile vs HD?

XNA is supported in 2010 / 2012 / 2013 now thanks to the MSXna project (http://msxna.codeplex.com/) just a quick vsix and supported client installs to enable.
It shouldn't matter what the version is as we only use VS2010 elements in the .sln / .csproj files anyway for MonoGame templates.

**Comment by nkast** [comment]
If the contentBuilder only use  VS2010 elements why not set it that it opens VS2010 when the .sln is double clicked? I haven't installed the MSXna to VS2012, what I did instead is use WP7 content projects to build my content which still works on VS2012. So, my proposal is: Turn the project into WP content project and use VS2010 as a .sln version. 
That way when someone clicks the .sln, it first opens on VS2010. If not install, it will open on VS2012 and still work. For 2013 I am afraid it will not work out of the box. (still, for VS2013 I copy the VS2012 version of XNA -WP7 only-  because of problems when debugging WP projects. The old XNA is messing with WP devices.)

What the change at the content link do if embed everything in the content folder. No need to link each asset separately. This could be a huge time saver during development. Sure, the sample now works just fine, but I hope the first sample to be used as guide/template for future samples.
The problem, as you said, is that we use a single content builder, the content folder could be filled with unrelated assets.

**Comment by nkast** [comment]
I believe the Reach format is sufficient for samples. In case a sample demonstrates a feature of HiDef (or other future profile/extension) it will require just that. 
I don't think samples should go beyond their scope and worry about fallback techniques, level of detail ,etc

**Comment by SimonDarksideJ** [comment]
Ok, in that case I'm fine with it. Merge away @tomspilman 
I'll also update the master branch with the last two changes and submit a separate pr for that.
I'll also include those changes in the forthcoming samples.

**Comment by tomspilman** [comment]
I can't merge this with the Activity changes for Android.  Those changes are in the develop branch where as this is the "master" branch which is aimed at the MonoGame 3.2 release.

**Comment by nkast** [comment]
I don't know why this is. I'll close it and resubmit. 
Maybe I should postpone this and wait till we have separate content directories for each project, cause in the way it is now, It will embed all assets founded in ContentBuilder.

**Comment by tomspilman** [comment]
We should just focus on https://github.com/Mono-Game/MonoGame.Samples/issues/8 to resolve this.

**Comment by SimonDarksideJ** [comment]
@nkast so how would you suggest changing the content directories?  can you be more specific?

**Comment by nkast** [comment]
@DDReaper I haven't though about it. Usually I don't have to care about multiple platforms, only a couple (W8/WP8/WP7/XNA). So far I really like the job you did with the separation of each project/platform.

Let's see, what do we need? 
1) Location of  "MGCB.exe"
2) Location of original content + hiDef content
3) Location of 'response' files
4) Location of outputDir
5) Location of  intermediateDir

**Comment by tomspilman** [comment]
> 3) Location of 'response' files

I suspect you mean the command file passed to `MGCB.exe`.  I haven't come up with a good name for those...  `.mgcb` files?  `.content` files?  The "response" file idea was copied from the C++ and C# command line compilers which work in a similar way to MGCB.

**Comment by nkast** [comment]
1) Location of "MGCB.exe"
i) include the  "MGCB.exe" somewhere in the samples. This is not done for the MonoGame assemplies so why should we do it for tools?
ii) Assume the path of  "MGCB.exe" is located at the official MG release directory.
iii) Assume the samples are installed side -by -side with MonoGame release and use a relative path
iv) Let the user set the PATH manually or in the Environment Variables.

2) Location of original content + hiDef content
They are now at '\MonoGame.Samples\Platformer2D\Content\'
This is good. hidef content can be places there too, side by side with the lowdef content either on another directory or with a different name. (ex. Gem.hiDef.png or Gem_128x128.png).
The 'response'  file will define -per platform- which one should be processed.
Usually you put there your highest quality assets and let content processor resize/resample/optimize.  

3) Location of 'response' files
Probably inside \MonoGame.Samples\Platformer2D\Platforms[platform]\content.response

4) Location of outputDir & intermediateDir
How about: 
\MonoGame.Samples\Platformer2D\Content\Bin[platform]\
\MonoGame.Samples\Platformer2D\Content\Obj[platform]\
Will this work?

**Comment by nkast** [comment]
@tomspilman Yeah. I try to use the same terminology as used at https://github.com/mono/MonoGame/wiki/MonoGame-Content-Builder

 .content is good.
.mgcb will make it possible to associate the file name with 'mgcb.exe' or other GUIs.

**Pull request closed without merging**
